### ISSUE TITLE
Movie suggestion

### ISSUE THREAD

**Issue by jhonata11** [jhonata11/web-player#1]
### Description 
The movie suggestion needs to be implemented. At first it has to: 
* Suggest a random movie (or list of movies).
* Offer a few filters for the movie to be suggested

### Tasks
- [x] add to menu.
- [x] add to the route file
- [x] create method on the controller
- [ ] implement method to return a movie (or maybe a list of movies).
- [ ] create the html to render the movies to be suggested 
- [ ] elaborate the graphic design for it to be pretty
